name: meuplanoai

services:
  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./backend/.env.development

  backend-test:
    container_name: backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    env_file:
      - ./backend/.env.development

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: 